openapi: 3.0.1
info:
  title: Attendance Management Microservice API
  version: 1.0.0
  description: API per la gestione delle presenze all'interno del sistema NewUnimol.

paths:
  /api/test:
    get:
      summary: Test dell'applicazione
      operationId: testEndpoint
      responses:
        '200':
          description: L'applicazione funziona correttamente
          content:
            text/plain:
              schema:
                type: string

  /api/createAttendance:
    post:
      summary: Crea nuova presenza
      operationId: createAttendance
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AttendanceCreateDTO'
            example:
              studentId: "12345"
              courseId: "67890"
              lessonDate: "2025-05-30"
              status: "present"
              orarioIngresso: "08:30:00"
      responses:
        '200':
          description: Presenza creata (compatibilità controller)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AttendanceDTO'
        '400':
          description: Dati non validi

  /api/updateAttendance/{attendanceId}:
    put:
      summary: Modifica presenza esistente
      operationId: updateAttendance
      parameters:
        - name: attendanceId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AttendanceUpdateDTO'
      responses:
        '200':
          description: Presenza aggiornata
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AttendanceDTO'
        '400':
          description: Modifica non consentita per incoerenza logica (es. entrata in ritardo su presenza, uscita anticipata su assenza)
          content:
            application/json:
              schema:
                type: string
              examples:
                entrataInRitardoNonConsentita:
                  value: Entrata in ritardo consentita solo su assenze
                uscitaAnticipataNonConsentita:
                  value: Uscita anticipata consentita solo su presenze
        '404':
          description: attendanceId errato o presenza non trovata
          content:
            application/json:
              schema:
                type: string
              example: attendanceId errato o presenza non trovata

  /api/deleteAttendance/{attendanceId}:
    delete:
      summary: Elimina una presenza
      operationId: deleteAttendance
      parameters:
        - name: attendanceId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Presenza eliminata
        '200':
          description: Presenza eliminata con successo (compatibilità controller)
        '404':
          description: attendanceId errato

  /api/getStudentAttendances/{studentId}:
    get:
      summary: Visualizza presenze per studente
      operationId: getStudentAttendances
      parameters:
        - name: studentId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Lista delle presenze
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AttendanceDTO'

  /api/getCourseAttendances/{courseId}:
    get:
      summary: Visualizza presenze per corso
      operationId: getCourseAttendances
      parameters:
        - name: courseId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Lista delle presenze
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AttendanceDTO'

  /api/attendances/student/{studentId}/course/{courseId}/attendance-percentage:
    get:
      summary: Percentuale presenze studente per corso
      operationId: getStudentCourseStatistics
      parameters:
        - name: studentId
          in: path
          required: true
          schema:
            type: string
        - name: courseId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Statistiche presenze
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AttendanceStatsDTO'

  /api/attendances/course/{courseId}/attendance-average:
    get:
      summary: Media presenze studenti per corso
      operationId: getCourseStatistics
      parameters:
        - name: courseId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Media presenze
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CourseAttendanceStatsDTO'

  /api/getAttendance/{attendanceId}:
    get:
      summary: Visualizza presenza tramite ID
      operationId: getAttendanceById
      parameters:
        - name: attendanceId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Dettaglio presenza
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AttendanceDTO'
        '404':
          description: Presenza non trovata

  /api/getAttendancesByDay/{date}:
    get:
      summary: Visualizza presenze per giorno
      operationId: getAttendancesByDay
      parameters:
        - name: date
          in: path
          required: true
          schema:
            type: string
            format: date
      responses:
        '200':
          description: Lista delle presenze per giorno
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AttendanceDTO'

components:
  schemas:
    AttendanceDTO:
      type: object
      properties:
        attendanceId:
          type: string
        studentId:
          type: string
        courseId:
          type: string
        lessonDate:
          type: string
          format: date
        status:
          type: string
          enum: [present, absent]
        orarioIngresso:
          type: string
          format: time
        orarioUscita:
          type: string
          format: time
      required:
        - studentId
        - courseId
        - lessonDate
        - status
        - orarioIngresso

    AttendanceCreateDTO:
      type: object
      properties:
        studentId:
          type: string
        courseId:
          type: string
        lessonDate:
          type: string
          format: date
        status:
          type: string
          enum: [present, absent]
        orarioIngresso:
          type: string
          format: time
        orarioUscita:
          type: string
          format: time
      required:
        - studentId
        - courseId
        - lessonDate
        - status
        - orarioIngresso

    AttendanceUpdateDTO:
      type: object
      properties:
        status:
          type: string
          enum: [present, absent]
        orarioIngresso:
          type: string
          format: time
        orarioUscita:
          type: string
          format: time

    AttendanceStatsDTO:
      type: object
      properties:
        studentId:
          type: string
        courseId:
          type: string
        attendancePercentage:
          type: number
          format: double
      required:
        - studentId
        - courseId
        - attendancePercentage
